using System;
using System.Linq;
using JsonGoddess.GeneratorTests.Harness;
using Xunit;

namespace JsonGoddess.GeneratorTests
{
    /// <summary>
    /// Утверждения о <b>тексте</b> порождаемого кода.
    ///
    /// Они нужны там, где round-trip ничего не заметит: и цепочка сравнений, и
    /// switch по ключу читают один и тот же документ одинаково, и отсутствие
    /// ветки на разделители тоже проявляется только в скорости. Проверять
    /// выбор формы поведением - значит не проверять его вовсе.
    /// </summary>
    public class GeneratedTextFixture
    {
        [Fact]
        public void Generated_code_compiles()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);
        }

        [Fact]
        public void Preamble_is_in_place()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);
            var text = run.SingleGeneratedFile;

            //сгенерированный код живёт в чужой сборке, и её настройки анализа -
            //не наше дело
            Assert.StartsWith("// <auto-generated/>", text, StringComparison.Ordinal);
            Assert.Contains("#pragma warning disable", text, StringComparison.Ordinal);
            Assert.Contains("#nullable enable", text, StringComparison.Ordinal);
        }

        [Fact]
        public void File_is_named_after_the_full_host_name()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);

            Assert.Equal("Demo.OrderSerializer.g.cs", run.GeneratedFiles.Keys.Single());
        }

        [Fact]
        public void Two_hosts_with_the_same_simple_name_in_different_namespaces_both_get_code()
        {
            var source = @"
using JsonGoddess;

namespace First
{
    public class Payload { public int Id { get; set; } }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}

namespace Second
{
    public class Payload { public int Id { get; set; } }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}
";

            var run = GeneratorHarness.Run(source);

            Assert.Empty(run.CompilationErrors);
            Assert.Equal(
                new[] { "First.Serializer.g.cs", "Second.Serializer.g.cs", },
                run.GeneratedFiles.Keys.OrderBy(k => k, StringComparer.Ordinal)
                );
        }

        /// <summary>
        /// Форма выбирается по набору имён, а не раз и навсегда: на форме, где
        /// длины разводят членов по корзинам, ключ измеренно проигрывает.
        /// </summary>
        [Fact]
        public void Distinct_name_lengths_get_a_chain_of_comparisons()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;

            Assert.Contains("switch (name.Length)", text, StringComparison.Ordinal);
            Assert.DoesNotContain("JsonNameKey.Compute", text, StringComparison.Ordinal);
        }

        [Fact]
        public void One_crowded_bucket_gets_a_switch_by_key()
        {
            var text = GeneratorHarness.Run(Sources.SameLength).SingleGeneratedFile;

            Assert.Contains("switch (name.Length)", text, StringComparison.Ordinal);
            Assert.Contains("JsonNameKey.Compute(name)", text, StringComparison.Ordinal);

            //имя в семь байт укладывается в ключ целиком, поэтому сравнения
            //спанов в этой форме не должно остаться ни одного
            Assert.DoesNotContain("SequenceEqual", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// Ключ имени длиннее семи байт - только префильтр, и два таких имени
        /// могут дать одну константу. Эмиттер обязан собрать их в одну ветку:
        /// два case с одним значением компилятор не примет.
        /// </summary>
        [Fact]
        public void Colliding_keys_share_one_case_and_are_separated_by_comparison()
        {
            var run = GeneratorHarness.Run(Sources.CollidingKeys);
            var text = run.SingleGeneratedFile;

            Assert.Empty(run.CompilationErrors);
            Assert.Contains("JsonNameKey.Compute(name)", text, StringComparison.Ordinal);

            var cases = text.Split('\n').Count(l => l.TrimStart().StartsWith("case 0x", StringComparison.Ordinal));
            Assert.Equal(1, cases);

            Assert.Contains("SequenceEqual(name, \"ReferenceA\"u8)", text, StringComparison.Ordinal);
            Assert.Contains("SequenceEqual(name, \"ReferenceD\"u8)", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// Структура документа - константа этапа компиляции: запятая и имя
        /// следующего свойства склеены в один литерал, и ни одной ветки на
        /// разделители в методе записи нет. Единственное ветвление - проверка
        /// самого объекта на null.
        /// </summary>
        [Fact]
        public void Writer_has_no_branch_on_separators()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;
            var writer = Section(text, "private static void Write_", "private static ");

            Assert.Equal(1, Occurrences(writer, "if ("));
            Assert.Contains("if (value is null)", writer, StringComparison.Ordinal);
            Assert.Contains("exhauster.AppendRaw(\"{\\\"Id\\\":\"u8);", writer, StringComparison.Ordinal);
            Assert.Contains("exhauster.AppendRaw(\",\\\"Paid\\\":\"u8);", writer, StringComparison.Ordinal);
        }

        /// <summary>
        /// Поддержка экранированных имён обязана стоять ноль на документах, где
        /// их нет, и это утверждение о <b>форме кода</b>, а не о скорости:
        /// разэкранирование стоит <b>после</b> диспетчера, на пути, по которому
        /// найденный член не идёт - он уходит по <c>goto next</c> раньше.
        ///
        /// Если проверку когда-нибудь перенесут перед switch'ем (так проще
        /// читается), round-trip этого не заметит, а каждый документ начнёт
        /// платить лишнюю ветку на каждое свойство.
        /// </summary>
        [Fact]
        public void Unescaping_a_name_sits_behind_the_dispatcher_not_in_front_of_it()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;

            var dispatcher = text.IndexOf("switch (name.Length)", StringComparison.Ordinal);
            var unescape = text.IndexOf("if (nameEscaped)", StringComparison.Ordinal);

            Assert.True(dispatcher >= 0 && unescape > dispatcher, "unescaping must come after the dispatcher");

            //второй заход в тот же switch, а не вторая его копия
            Assert.Contains("goto dispatch;", text, StringComparison.Ordinal);
            Assert.Equal(1, Occurrences(text, "switch (name.Length)"));
        }

        [Fact]
        public void Non_ascii_names_stay_ascii_in_the_source_but_keep_their_utf8_bytes()
        {
            var run = GeneratorHarness.Run(
                Sources.Host(@"        [JsonPropertyName(""имя"")] public string? Name { get; set; }")
                );

            var text = run.SingleGeneratedFile;

            Assert.Empty(run.CompilationErrors);

            //литерал печатается escape-последовательностями, а не сырыми
            //символами: как именно файл прочитают на чужой машине, мы не знаем,
            //а u8-литерал компилятор кодирует в UTF-8 сам, и \uXXXX даёт ровно
            //те байты, которые приедут из документа
            Assert.Contains("\\u0438\\u043C\\u044F", text, StringComparison.Ordinal);
            Assert.DoesNotContain("имя", text, StringComparison.Ordinal);
        }

        [Fact]
        public void Every_builtin_is_served()
        {
            var run = GeneratorHarness.Run(
                Sources.Host(@"
        public bool Bool { get; set; }
        public sbyte SByte { get; set; }
        public byte Byte { get; set; }
        public short Short { get; set; }
        public ushort UShort { get; set; }
        public int Int { get; set; }
        public uint UInt { get; set; }
        public long Long { get; set; }
        public ulong ULong { get; set; }
        public float Float { get; set; }
        public double Double { get; set; }
        public decimal Decimal { get; set; }
        public char Char { get; set; }
        public string? String { get; set; }
        public DateTime DateTime { get; set; }
        public DateTimeOffset DateTimeOffset { get; set; }
        public TimeSpan TimeSpan { get; set; }
        public Guid Guid { get; set; }
        public byte[]? Bytes { get; set; }
        public int? NullableInt { get; set; }
        public Guid? NullableGuid { get; set; }
")
                );

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);
        }

        private static string Section(string text, string from, string until)
        {
            var start = text.IndexOf(from, StringComparison.Ordinal);
            Assert.True(start >= 0, "marker not found: " + from);

            var end = text.IndexOf(until, start + from.Length, StringComparison.Ordinal);
            return end < 0 ? text.Substring(start) : text.Substring(start, end - start);
        }

        private static int Occurrences(string text, string needle)
        {
            var count = 0;
            for (var i = text.IndexOf(needle, StringComparison.Ordinal); i >= 0;
                i = text.IndexOf(needle, i + needle.Length, StringComparison.Ordinal))
            {
                count++;
            }

            return count;
        }
    }
}
