using System;
using System.Linq;
using JsonGoddess.GeneratorTests.Harness;
using Xunit;

namespace JsonGoddess.GeneratorTests
{
    /// <summary>
    /// Утверждения о <b>тексте</b> порождаемого кода.
    ///
    /// Они нужны там, где round-trip ничего не заметит: и цепочка сравнений, и
    /// switch по ключу читают один и тот же документ одинаково, и отсутствие
    /// ветки на разделители тоже проявляется только в скорости. Проверять
    /// выбор формы поведением - значит не проверять его вовсе.
    /// </summary>
    public class GeneratedTextFixture
    {
        [Fact]
        public void Generated_code_compiles()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);
        }

        [Fact]
        public void Preamble_is_in_place()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);
            var text = run.SingleGeneratedFile;

            //сгенерированный код живёт в чужой сборке, и её настройки анализа -
            //не наше дело
            Assert.StartsWith("// <auto-generated/>", text, StringComparison.Ordinal);
            Assert.Contains("#pragma warning disable", text, StringComparison.Ordinal);
            Assert.Contains("#nullable enable", text, StringComparison.Ordinal);
        }

        [Fact]
        public void File_is_named_after_the_full_host_name()
        {
            var run = GeneratorHarness.Run(Sources.DistinctLengths);

            Assert.Equal("Demo.OrderSerializer.g.cs", run.GeneratedFiles.Keys.Single());
        }

        [Fact]
        public void Two_hosts_with_the_same_simple_name_in_different_namespaces_both_get_code()
        {
            var source = @"
using JsonGoddess;

namespace First
{
    public class Payload { public int Id { get; set; } }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}

namespace Second
{
    public class Payload { public int Id { get; set; } }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}
";

            var run = GeneratorHarness.Run(source);

            Assert.Empty(run.CompilationErrors);
            Assert.Equal(
                new[] { "First.Serializer.g.cs", "Second.Serializer.g.cs", },
                run.GeneratedFiles.Keys.OrderBy(k => k, StringComparer.Ordinal)
                );
        }

        /// <summary>
        /// Форма выбирается по набору имён, а не раз и навсегда: на форме, где
        /// длины разводят членов по корзинам, ключ измеренно проигрывает.
        /// </summary>
        [Fact]
        public void Distinct_name_lengths_get_a_chain_of_comparisons()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;

            Assert.Contains("switch (name.Length)", text, StringComparison.Ordinal);
            Assert.DoesNotContain("JsonNameKey.Compute", text, StringComparison.Ordinal);
        }

        [Fact]
        public void One_crowded_bucket_gets_a_switch_by_key()
        {
            var text = GeneratorHarness.Run(Sources.SameLength).SingleGeneratedFile;

            Assert.Contains("switch (name.Length)", text, StringComparison.Ordinal);
            Assert.Contains("JsonNameKey.Compute(name)", text, StringComparison.Ordinal);

            //имя в семь байт укладывается в ключ целиком, поэтому сравнения
            //спанов в этой форме не должно остаться ни одного
            Assert.DoesNotContain("SequenceEqual", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// Ключ имени длиннее семи байт - только префильтр, и два таких имени
        /// могут дать одну константу. Эмиттер обязан собрать их в одну ветку:
        /// два case с одним значением компилятор не примет.
        /// </summary>
        [Fact]
        public void Colliding_keys_share_one_case_and_are_separated_by_comparison()
        {
            var run = GeneratorHarness.Run(Sources.CollidingKeys);
            var text = run.SingleGeneratedFile;

            Assert.Empty(run.CompilationErrors);
            Assert.Contains("JsonNameKey.Compute(name)", text, StringComparison.Ordinal);

            var cases = text.Split('\n').Count(l => l.TrimStart().StartsWith("case 0x", StringComparison.Ordinal));
            Assert.Equal(1, cases);

            Assert.Contains("SequenceEqual(name, \"ReferenceA\"u8)", text, StringComparison.Ordinal);
            Assert.Contains("SequenceEqual(name, \"ReferenceD\"u8)", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// Структура документа - константа этапа компиляции: запятая и имя
        /// следующего свойства склеены в один литерал, и ни одной ветки на
        /// разделители в методе записи нет. Единственное ветвление - проверка
        /// самого объекта на null.
        /// </summary>
        [Fact]
        public void Writer_has_no_branch_on_separators()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;
            var writer = Section(text, "private static void Write_", "private static ");

            Assert.Equal(1, Occurrences(writer, "if ("));
            Assert.Contains("if (value is null)", writer, StringComparison.Ordinal);
            Assert.Contains("exhauster.AppendRaw(\"{\\\"Id\\\":\"u8);", writer, StringComparison.Ordinal);
            Assert.Contains("exhauster.AppendRaw(\",\\\"Paid\\\":\"u8);", writer, StringComparison.Ordinal);
        }

        /// <summary>
        /// Поддержка экранированных имён обязана стоять ноль на документах, где
        /// их нет, и это утверждение о <b>форме кода</b>, а не о скорости:
        /// разэкранирование стоит <b>после</b> диспетчера, на пути, по которому
        /// найденный член не идёт - он уходит по <c>goto next</c> раньше.
        ///
        /// Если проверку когда-нибудь перенесут перед switch'ем (так проще
        /// читается), round-trip этого не заметит, а каждый документ начнёт
        /// платить лишнюю ветку на каждое свойство.
        /// </summary>
        [Fact]
        public void Unescaping_a_name_sits_behind_the_dispatcher_not_in_front_of_it()
        {
            var text = GeneratorHarness.Run(Sources.DistinctLengths).SingleGeneratedFile;

            var dispatcher = text.IndexOf("switch (name.Length)", StringComparison.Ordinal);
            var unescape = text.IndexOf("if (nameEscaped)", StringComparison.Ordinal);

            Assert.True(dispatcher >= 0 && unescape > dispatcher, "unescaping must come after the dispatcher");

            //второй заход в тот же switch, а не вторая его копия
            Assert.Contains("goto dispatch;", text, StringComparison.Ordinal);
            Assert.Equal(1, Occurrences(text, "switch (name.Length)"));
        }

        [Fact]
        public void Non_ascii_names_stay_ascii_in_the_source_but_keep_their_utf8_bytes()
        {
            var run = GeneratorHarness.Run(
                Sources.Host(@"        [JsonPropertyName(""имя"")] public string? Name { get; set; }")
                );

            var text = run.SingleGeneratedFile;

            Assert.Empty(run.CompilationErrors);

            //литерал печатается escape-последовательностями, а не сырыми
            //символами: как именно файл прочитают на чужой машине, мы не знаем,
            //а u8-литерал компилятор кодирует в UTF-8 сам, и \uXXXX даёт ровно
            //те байты, которые приедут из документа
            Assert.Contains("\\u0438\\u043C\\u044F", text, StringComparison.Ordinal);
            Assert.DoesNotContain("имя", text, StringComparison.Ordinal);
        }

        [Fact]
        public void Every_builtin_is_served()
        {
            var run = GeneratorHarness.Run(
                Sources.Host(@"
        public bool Bool { get; set; }
        public sbyte SByte { get; set; }
        public byte Byte { get; set; }
        public short Short { get; set; }
        public ushort UShort { get; set; }
        public int Int { get; set; }
        public uint UInt { get; set; }
        public long Long { get; set; }
        public ulong ULong { get; set; }
        public float Float { get; set; }
        public double Double { get; set; }
        public decimal Decimal { get; set; }
        public char Char { get; set; }
        public string? String { get; set; }
        public DateTime DateTime { get; set; }
        public DateTimeOffset DateTimeOffset { get; set; }
        public TimeSpan TimeSpan { get; set; }
        public Guid Guid { get; set; }
        public byte[]? Bytes { get; set; }
        public int? NullableInt { get; set; }
        public Guid? NullableGuid { get; set; }
")
                );

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);
        }

        /// <summary>
        /// Читатель коллекции - метод, и метод <b>один на тип</b>, а не на
        /// член: две коллекции одного типа в одном объекте обязаны звать один и
        /// тот же <c>ReadCollection_</c>, иначе объём порождаемого кода начнёт
        /// расти по числу членов, а не по числу типов.
        /// </summary>
        [Fact]
        public void One_collection_reader_per_type_not_per_member()
        {
            var run = GeneratorHarness.Run(Sources.Composite);
            var text = run.SingleGeneratedFile;

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);

            Assert.Equal(1, Occurrences(text, "private static global::System.Collections.Generic.List<global::Demo.Line>? ReadCollection_"));
            Assert.Equal(2, Occurrences(text, "ReadCollection_ListOf_Demo_Line(injector"));
        }

        /// <summary>
        /// Вложенная коллекция - не частный случай: внешний читатель зовёт
        /// внутренний, и глубина ограничена только самим типом.
        /// </summary>
        [Fact]
        public void Nested_collection_gets_a_reader_at_every_level()
        {
            var text = GeneratorHarness.Run(Sources.Composite).SingleGeneratedFile;

            Assert.Contains("ReadCollection_ListOf_ListOf_Int32(", text, StringComparison.Ordinal);
            Assert.Contains("ReadCollection_ListOf_Int32(", text, StringComparison.Ordinal);

            var outer = Section(text, "ReadCollection_ListOf_ListOf_Int32(\n", "private static ");
            Assert.Contains("item = ReadCollection_ListOf_Int32(", outer, StringComparison.Ordinal);
        }

        /// <summary>
        /// <c>byte[]</c> - единственный массив, который остаётся base64-строкой.
        /// Превратить его в список чисел значило бы выдать другой документ, и
        /// round-trip этого не заметил бы: сам себя мы прочитали бы обратно.
        /// </summary>
        [Fact]
        public void Byte_array_stays_base64_and_gets_no_collection_reader()
        {
            var text = GeneratorHarness.Run(Sources.Composite).SingleGeneratedFile;

            Assert.Contains("exhauster.AppendBase64(value.Payload);", text, StringComparison.Ordinal);
            Assert.DoesNotContain("ReadCollection_ArrayOf_Byte", text, StringComparison.Ordinal);
            Assert.Contains("ReadCollection_ArrayOf_Int32", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// Запись коллекции печатается по месту, а не вызовом: длина
        /// коллекции - единственное, чего этап компиляции не знает, и цена
        /// этого незнания должна ограничиваться одной веткой на элемент.
        /// </summary>
        [Fact]
        public void Collections_are_written_in_place_with_one_branch_per_element()
        {
            var text = GeneratorHarness.Run(Sources.Composite).SingleGeneratedFile;
            var writer = Section(text, "private static void Write_Demo_Basket(", "private static void Write_Demo_Line(");

            Assert.DoesNotContain("WriteCollection_", writer, StringComparison.Ordinal);

            //Lines, Backorder, Numbers плюс Matrix внешняя и внутренняя - пять
            //циклов; Head коллекцией не является и цикла не получает
            Assert.Equal(5, Occurrences(writer, "for (var i"));
            Assert.Equal(5, Occurrences(writer, "> 0)"));
        }

        [Fact]
        public void Self_referencing_subject_produces_mutually_recursive_code()
        {
            var run = GeneratorHarness.Run(@"
using System.Collections.Generic;
using JsonGoddess;

namespace Demo
{
    public class Node
    {
        public int Id { get; set; }
        public List<Node>? Children { get; set; }
    }

    [JsonSubject(typeof(Node), true)]
    public partial class NodeSerializer { }
}
");

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);
            Assert.Contains("item = Read_Demo_Node(injector", run.SingleGeneratedFile, StringComparison.Ordinal);
        }

        /// <summary>
        /// Числовой enum метода не получает: он и есть одно приведение к
        /// подлежащему типу плюс та же перегрузка <c>Append</c>, что у числа.
        /// Вынести это в метод значило бы добавить вызов туда, где кода на одну
        /// строку.
        /// </summary>
        [Fact]
        public void Numeric_enum_is_written_in_place_as_its_underlying_type()
        {
            var run = GeneratorHarness.Run(@"
using JsonGoddess;

namespace Demo
{
    public enum Status : byte { Draft, Sent }

    public class Payload
    {
        public Status Value { get; set; }
        public Status? Maybe { get; set; }
    }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}
");

            var text = run.SingleGeneratedFile;

            Assert.Empty(run.CompilationErrors);
            Assert.Contains("exhauster.Append((byte)value.Value);", text, StringComparison.Ordinal);
            Assert.Contains("exhauster.Append((byte?)value.Maybe);", text, StringComparison.Ordinal);
            Assert.DoesNotContain("ReadEnum_", text, StringComparison.Ordinal);
            Assert.DoesNotContain("WriteEnum_", text, StringComparison.Ordinal);
        }

        /// <summary>
        /// А строковый получает - и получает <b>один</b> на тип, сколько бы
        /// членов на него ни ссылалось.
        ///
        /// Способ сравнения выбирается по члену, а не по типу: имя из
        /// <c>[JsonStringEnumMemberName]</c> эталон принимает только в
        /// точности, C#-идентификатор - в любом регистре. Разницу видно только
        /// здесь: round-trip прочитает документ и так, и так.
        /// </summary>
        [Fact]
        public void String_enum_folds_case_only_for_names_that_came_from_csharp()
        {
            var run = GeneratorHarness.Run(@"
using JsonGoddess;
using System.Text.Json.Serialization;

namespace Demo
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum Mode
    {
        Draft,

        [JsonStringEnumMemberName(""sent-out"")]
        Forwarded,
    }

    public class Payload
    {
        public Mode First { get; set; }
        public Mode Second { get; set; }
    }

    [JsonSubject(typeof(Payload), true)]
    public partial class Serializer { }
}
");

            var text = run.SingleGeneratedFile;

            Assert.Empty(run.GeneratorDiagnostics);
            Assert.Empty(run.CompilationErrors);

            Assert.Equal(1, Occurrences(text, "private static global::Demo.Mode ReadEnum_Demo_Mode("));
            Assert.Equal(2, Occurrences(text, "= ReadEnum_Demo_Mode(injector"));

            Assert.Contains("JsonAsciiName.EqualsIgnoreCase(raw, \"Draft\"u8)", text, StringComparison.Ordinal);
            Assert.Contains("SequenceEqual(raw, \"sent-out\"u8)", text, StringComparison.Ordinal);
            Assert.DoesNotContain("EqualsIgnoreCase(raw, \"sent-out\"u8)", text, StringComparison.Ordinal);

            //значение вне набора эталон пишет числом, и мы обязаны так же
            Assert.Contains("exhauster.Append((int)value);", text, StringComparison.Ordinal);
        }

        private static string Section(string text, string from, string until)
        {
            var start = text.IndexOf(from, StringComparison.Ordinal);
            Assert.True(start >= 0, "marker not found: " + from);

            var end = text.IndexOf(until, start + from.Length, StringComparison.Ordinal);
            return end < 0 ? text.Substring(start) : text.Substring(start, end - start);
        }

        private static int Occurrences(string text, string needle)
        {
            var count = 0;
            for (var i = text.IndexOf(needle, StringComparison.Ordinal); i >= 0;
                i = text.IndexOf(needle, i + needle.Length, StringComparison.Ordinal))
            {
                count++;
            }

            return count;
        }
    }
}
