using System.Collections.Generic;
using System.Linq;
using JsonGoddess.Generator.Model;

namespace JsonGoddess.Generator.Emit
{
    /// <summary>
    /// Печатает partial-часть хоста целиком.
    ///
    /// Преамбула здесь не формальность: сгенерированный код живёт в чужой
    /// сборке, и её настройки анализа - не наше дело. <c>&lt;auto-generated/&gt;</c>
    /// плюс общее подавление предупреждений означают, что подключение
    /// JsonGoddess не может испортить чужую сборку с
    /// <c>TreatWarningsAsErrors</c>.
    /// </summary>
    public static class ClassSourceProducer
    {
        private const string Scan = BuiltinSourceProducer.Scan;
        private const string Context = "global::JsonGoddess.JsonParseContext";
        private const string Span = "global::System.ReadOnlySpan<byte>";

        public static string Produce(HostModel host)
        {
            var builder = new SourceBuilder();

            builder.Line("// <auto-generated/>");
            builder.Line("#pragma warning disable");
            builder.Line("#nullable enable");
            builder.Line();

            var hasNamespace = !string.IsNullOrEmpty(host.Namespace);
            if (hasNamespace)
            {
                builder.OpenBlock("namespace " + host.Namespace);
            }

            builder.OpenBlock(host.TypeName);

            foreach (var exhauster in host.ExhausterTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitSerializeEntry(builder, subject, exhauster);
                    }

                    EmitWriter(builder, subject, exhauster);
                }
            }

            foreach (var injector in host.InjectorTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitDeserializeEntry(builder, subject, injector);
                    }

                    EmitReader(builder, subject, injector);
                }
            }

            builder.CloseBlock();

            if (hasNamespace)
            {
                builder.CloseBlock();
            }

            return builder.ToString();
        }

        private static void EmitSerializeEntry(SourceBuilder builder, SubjectModel subject, string exhauster)
        {
            builder.OpenBlock(
                "public static void Serialize(" + exhauster + " exhauster, " + subject.FullName + "? value)"
                );
            builder.Line("Write_" + subject.MethodSuffix + "(exhauster, value);");
            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitDeserializeEntry(SourceBuilder builder, SubjectModel subject, string injector)
        {
            builder.OpenBlock(
                "public static void Deserialize(" + injector + " injector, " + Span + " json, out "
                + subject.FullName + "? result)"
                );
            builder.Line("var position = 0;");
            builder.Line("var context = new " + Context + "(json);");

            //try/finally здесь стоит один раз на документ, а не на член:
            //контекст арендует буфер только если в документе попалось
            //экранированное имя, но вернуть арендованное надо в любом случае
            builder.OpenBlock("try");
            builder.Line("result = Read_" + subject.MethodSuffix + "(injector, json, ref position, ref context);");
            builder.CloseBlock();
            builder.OpenBlock("finally");
            builder.Line("context.Release();");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Запись. Разделители склеены с именами свойств в один
        /// UTF-8-литерал: структура документа известна на этапе компиляции, и
        /// автомата состояний, стека глубины и проверки "нужна ли запятая"
        /// здесь нет вовсе - в отличие от <c>Utf8JsonWriter</c>, который не
        /// знает, что ему напишут следующим.
        ///
        /// Ни одной ветки на разделители в фазе 2 не бывает и по второй
        /// причине: условно опускаемых членов ещё нет, поэтому запятые
        /// безусловны.
        /// </summary>
        private static void EmitWriter(SourceBuilder builder, SubjectModel subject, string exhauster)
        {
            var members = subject.Members.Where(m => m.CanWrite).ToList();

            builder.OpenBlock(
                "private static void Write_" + subject.MethodSuffix + "("
                + exhauster + " exhauster, " + subject.FullName + "? value)"
                );

            builder.OpenBlock("if (value is null)");
            builder.Line("exhauster.AppendNull();");
            builder.Line("return;");
            builder.CloseBlock();
            builder.Line();

            if (members.Count == 0)
            {
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{}") + ");");
                builder.CloseBlock();
                builder.Line();
                return;
            }

            for (var i = 0; i < members.Count; i++)
            {
                var member = members[i];
                var prefix = (i == 0 ? "{" : ",") + "\"" + member.JsonName + "\":";

                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(prefix) + ");");
                BuiltinSourceProducer.WriteValue(builder, member, "value." + member.MemberName);
            }

            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("}") + ");");
            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitReader(SourceBuilder builder, SubjectModel subject, string injector)
        {
            var members = subject.Members.Where(m => m.CanRead).ToList();

            builder.Line("private static " + subject.FullName + "? Read_" + subject.MethodSuffix + "(");
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            builder.OpenBlock("if (" + Scan + ".TryReadNull(json, ref position))");
            builder.Line("return null;");
            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".OpenBrace);");
            builder.Line("var result = new " + subject.FullName + "();");
            builder.Line();

            builder.OpenBlock("if (" + Scan + ".TryConsume(json, ref position, " + Scan + ".CloseBrace))");
            builder.Line("return result;");
            builder.CloseBlock();
            builder.Line();

            builder.OpenBlock("while (true)");

            builder.Line("var name = " + Scan + ".ReadStringContent(json, ref position, out var nameEscaped);");
            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
            builder.Line();

            if (members.Count > 0)
            {
                builder.Unindent();
                builder.Line("dispatch:");
                builder.Indent();

                NameDispatcher.Emit(
                    builder,
                    members,
                    member => BuiltinSourceProducer.ReadValue(builder, member, "result." + member.MemberName)
                    );

                //Экранированное имя не совпадёт ни с одним литералом, потому
                //что литералы печатаются из имён, которым escape не нужен.
                //Значит управление доходит сюда само, и разэкранирование
                //оказывается ровно там, где оно и должно быть: на пути, по
                //которому обычный документ не идёт ни разу. Член, который
                //нашёлся, ушёл по goto раньше.
                //
                //Второй заход в тот же switch, а не второй switch: копия
                //диспетчера удвоила бы объём порождаемого кода ради случая,
                //который почти не встречается.
                builder.OpenBlock("if (nameEscaped)");
                builder.Line("nameEscaped = false;");
                builder.Line("name = context.UnescapeName(name);");
                builder.Line("goto dispatch;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line(Scan + ".SkipValue(json, ref position);");
            builder.Line();

            builder.Unindent();
            builder.Line("next:");
            builder.Indent();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".CloseBrace);");
            builder.Line("return result;");

            builder.CloseBlock();
            builder.Line();
        }
    }
}
