using System.Collections.Generic;
using System.Linq;
using JsonGoddess.Generator.Binding;
using JsonGoddess.Generator.Model;
using JsonGoddess.Generator.Shared;

namespace JsonGoddess.Generator.Emit
{
    /// <summary>
    /// Печатает partial-часть хоста целиком.
    ///
    /// Преамбула здесь не формальность: сгенерированный код живёт в чужой
    /// сборке, и её настройки анализа - не наше дело. <c>&lt;auto-generated/&gt;</c>
    /// плюс общее подавление предупреждений означают, что подключение
    /// JsonGoddess не может испортить чужую сборку с
    /// <c>TreatWarningsAsErrors</c>.
    /// </summary>
    public static class ClassSourceProducer
    {
        private const string Scan = ValueSourceProducer.Scan;
        private const string TokenKind = "global::JsonGoddess.Internal.JsonTokenKind";
        private const string AsciiName = "global::JsonGoddess.Internal.JsonAsciiName";
        private const string Context = "global::JsonGoddess.JsonParseContext";
        private const string Span = "global::System.ReadOnlySpan<byte>";
        private const string EqualityComparer = "global::System.Collections.Generic.EqualityComparer";

        public static string Produce(HostModel host)
        {
            var builder = new SourceBuilder();

            builder.Line("// <auto-generated/>");
            builder.Line("#pragma warning disable");
            builder.Line("#nullable enable");
            builder.Line();

            var hasNamespace = !string.IsNullOrEmpty(host.Namespace);
            if (hasNamespace)
            {
                builder.OpenBlock("namespace " + host.Namespace);
            }

            builder.OpenBlock(host.TypeName);

            foreach (var exhauster in host.ExhausterTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitSerializeEntry(builder, subject, exhauster);
                    }

                    EmitWriter(builder, subject, exhauster, host.DictionaryKeyNaming);
                }

                foreach (var enumModel in host.StringEnums)
                {
                    EmitEnumWriter(builder, enumModel, exhauster);
                }
            }

            foreach (var injector in host.InjectorTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitDeserializeEntry(builder, subject, injector);
                    }

                    EmitReader(builder, subject, injector);
                }

                foreach (var collection in host.Collections)
                {
                    EmitCollectionReader(builder, collection, injector);
                }

                foreach (var enumModel in host.StringEnums)
                {
                    EmitEnumReader(builder, enumModel, injector);
                }
            }

            builder.CloseBlock();

            if (hasNamespace)
            {
                builder.CloseBlock();
            }

            return builder.ToString();
        }

        private static void EmitSerializeEntry(SourceBuilder builder, SubjectModel subject, string exhauster)
        {
            builder.OpenBlock(
                "public static void Serialize(" + exhauster + " exhauster, " + subject.Declaration + " value)"
                );
            builder.Line("Write_" + subject.MethodSuffix + "(exhauster, value);");
            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitDeserializeEntry(SourceBuilder builder, SubjectModel subject, string injector)
        {
            builder.OpenBlock(
                "public static void Deserialize(" + injector + " injector, " + Span + " json, out "
                + subject.Declaration + " result)"
                );
            builder.Line("var position = 0;");
            builder.Line("var context = new " + Context + "(json);");

            //try/finally здесь стоит один раз на документ, а не на член:
            //контекст арендует буфер только если в документе попалось
            //экранированное имя, но вернуть арендованное надо в любом случае
            builder.OpenBlock("try");
            builder.Line("result = Read_" + subject.MethodSuffix + "(injector, json, ref position, ref context);");
            builder.CloseBlock();
            builder.OpenBlock("finally");
            builder.Line("context.Release();");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Запись. Разделители склеены с именами свойств в один
        /// UTF-8-литерал: структура документа известна на этапе компиляции, и
        /// автомата состояний, стека глубины и проверки "нужна ли запятая"
        /// здесь нет вовсе - в отличие от <c>Utf8JsonWriter</c>, который не
        /// знает, что ему напишут следующим.
        ///
        /// Ни одной ветки на разделители в фазе 2 не бывает и по второй
        /// причине: условно опускаемых членов ещё нет, поэтому запятые
        /// безусловны.
        /// </summary>
        private static void EmitWriter(
            SourceBuilder builder,
            SubjectModel subject,
            string exhauster,
            JsonNamingStyle keyNaming
            )
        {
            var members = subject.Members.Where(m => m.CanWrite).ToList();

            builder.OpenBlock(
                "private static void Write_" + subject.MethodSuffix + "("
                + exhauster + " exhauster, " + subject.Declaration + " value)"
                );

            //у структуры проверки нет, и это не экономия ветки: значение
            //структуры null описать не может, а Nullable<> над ней разбирается
            //на месте члена, до вызова
            if (!subject.IsValueType)
            {
                builder.OpenBlock("if (value is null)");
                builder.Line("exhauster.AppendNull();");
                builder.Line("return;");
                builder.CloseBlock();
                builder.Line();
            }

            if (members.Count == 0)
            {
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{}") + ");");
                builder.CloseBlock();
                builder.Line();
                return;
            }

            //Состояние на этапе компиляции, а не в рантайме. pendingOpen -
            //фигурная скобка ещё не напечатана и склеится с именем первого
            //члена; commaIsCertain - до этого места точно что-то написано, и
            //запятая снова становится частью литерала.
            var pendingOpen = true;
            var commaIsCertain = false;
            var needCommaDeclared = false;

            for (var i = 0; i < members.Count; i++)
            {
                var member = members[i];

                if (member.Condition == WriteCondition.Always)
                {
                    //скобка склеивается с именем первого члена только здесь: у
                    //условного члена она обязана быть напечатана снаружи его
                    //ветки, иначе объект без членов остался бы без скобки
                    var literal = (pendingOpen ? "{" : commaIsCertain ? "," : string.Empty)
                        + "\"" + member.JsonName + "\":";

                    if (!pendingOpen && !commaIsCertain && needCommaDeclared)
                    {
                        builder.OpenBlock("if (needComma)");
                        builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(",") + ");");
                        builder.CloseBlock();
                        builder.Line();
                    }

                    builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(literal) + ");");
                    ValueSourceProducer.WriteValue(builder, member.Value, "value." + member.MemberName, 0, keyNaming);

                    pendingOpen = false;
                    commaIsCertain = true;
                    continue;
                }

                if (pendingOpen)
                {
                    builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{") + ");");
                    pendingOpen = false;
                }

                if (!commaIsCertain && !needCommaDeclared)
                {
                    builder.Line("var needComma = false;");
                    needCommaDeclared = true;
                }

                builder.Line();

                var candidate = "candidate" + i;
                var conditionalLiteral = (commaIsCertain ? "," : string.Empty)
                    + "\"" + member.JsonName + "\":";

                builder.OpenBlock();
                builder.Line("var " + candidate + " = value." + member.MemberName + ";");
                builder.OpenBlock("if (" + Condition(member, candidate) + ")");

                if (!commaIsCertain)
                {
                    //у самого первого члена needComma заведомо false, и ветка
                    //здесь была бы веткой ради симметрии
                    if (i > 0)
                    {
                        builder.OpenBlock("if (needComma)");
                        builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(",") + ");");
                        builder.CloseBlock();
                        builder.Line();
                    }

                    builder.Line("needComma = true;");
                }

                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(conditionalLiteral) + ");");
                ValueSourceProducer.WriteValue(builder, member.Value, candidate, 0, keyNaming);

                builder.CloseBlock();
                builder.CloseBlock();
                builder.Line();
            }

            if (pendingOpen)
            {
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{") + ");");
            }

            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("}") + ");");
            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Условие записи. Для <c>default</c> сравнение печатается прямое, а не
        /// через <c>EqualityComparer&lt;T&gt;.Default</c>: тип известен, и на
        /// всех обслуживаемых типах <c>!=</c> даёт тот же ответ - включая
        /// <c>-0.0</c>, который эталон тоже опускает.
        /// </summary>
        private static string Condition(MemberModel member, string candidate)
        {
            if (member.Condition == WriteCondition.WhenNotNull || member.Value.IsNullable)
            {
                return candidate + " is not null";
            }

            //Структура-субъект: у неё нет operator !=, и печатать сравнение
            //значило бы выдать код, который не компилируется. Эталон в этом
            //месте сравнивает через EqualityComparer<T>.Default - проверено
            //прогоном: структура в значении по умолчанию из документа
            //исчезает, - и цена его вызова тут уместна, потому что платит за
            //неё тот, кто явно написал WhenWritingDefault на структуре.
            if (member.Value.IsValueType)
            {
                return "!" + EqualityComparer + "<" + member.Value.TypeName + ">.Default.Equals("
                    + candidate + ", default(" + member.Value.TypeName + "))";
            }

            return candidate + " != default(" + member.Value.TypeName + ")";
        }

        private static void EmitReader(SourceBuilder builder, SubjectModel subject, string injector)
        {
            var members = subject.Members.Where(m => m.CanRead).ToList();

            builder.Line("private static " + subject.Declaration + " Read_" + subject.MethodSuffix + "(");
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            //У структуры ветки на null нет, и это тоже не экономия: null на
            //месте структуры обязан кончиться отказом - ровно так ведёт себя
            //эталон, - и он кончается им сам, на Expect(OpenBrace) ниже.
            //Nullable<> над структурой разбирается на месте члена, до вызова.
            if (!subject.IsValueType)
            {
                builder.OpenBlock("if (" + Scan + ".TryReadNull(json, ref position))");
                builder.Line("return null;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".OpenBrace);");

            var deferred = subject.NeedsDeferredConstruction;

            if (deferred)
            {
                EmitDeferredLocals(builder, subject, members);
            }
            else
            {
                builder.Line("var result = new " + subject.FullName + "();");
                builder.Line();
            }

            builder.OpenBlock("if (" + Scan + ".TryConsume(json, ref position, " + Scan + ".CloseBrace))");
            builder.Line(deferred ? "return " + Construct(subject, members) + ";" : "return result;");
            builder.CloseBlock();
            builder.Line();

            builder.OpenBlock("while (true)");

            builder.Line("var name = " + Scan + ".ReadStringContent(json, ref position, out var nameEscaped);");
            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
            builder.Line();

            if (members.Count > 0)
            {
                builder.Unindent();
                builder.Line("dispatch:");
                builder.Indent();

                NameDispatcher.Emit(
                    builder,
                    members,
                    member =>
                    {
                        ValueSourceProducer.ReadValue(builder, member.Value, Target(member, deferred));

                        if (deferred && !member.IsConstructorParameter)
                        {
                            builder.Line(Seen(member) + " = true;");
                        }
                    }
                    );

                //Экранированное имя не совпадёт ни с одним литералом, потому
                //что литералы печатаются из имён, которым escape не нужен.
                //Значит управление доходит сюда само, и разэкранирование
                //оказывается ровно там, где оно и должно быть: на пути, по
                //которому обычный документ не идёт ни разу. Член, который
                //нашёлся, ушёл по goto раньше.
                //
                //Второй заход в тот же switch, а не второй switch: копия
                //диспетчера удвоила бы объём порождаемого кода ради случая,
                //который почти не встречается.
                builder.OpenBlock("if (nameEscaped)");
                builder.Line("nameEscaped = false;");
                builder.Line("name = context.UnescapeName(name);");
                builder.Line("goto dispatch;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line(Scan + ".SkipValue(json, ref position);");
            builder.Line();

            builder.Unindent();
            builder.Line("next:");
            builder.Indent();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".CloseBrace);");

            if (deferred)
            {
                builder.Line();
                builder.Line("var result = " + Construct(subject, members) + ";");

                foreach (var member in members.Where(m => !m.IsConstructorParameter))
                {
                    builder.OpenBlock("if (" + Seen(member) + ")");
                    builder.Line("result." + member.MemberName + " = " + Assigned(member) + ";");
                    builder.CloseBlock();
                }
            }

            builder.Line("return result;");

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Локальные отложенной формы: по одной на каждый читаемый член, плюс
        /// флаг присутствия на тех, кого присваивает не конструктор.
        ///
        /// Аргумент заводится <b>объявленным умолчанием параметра</b>, и это
        /// заменяет флаг для него целиком: не было имени в документе -
        /// осталось умолчание, ровно как у эталона (проверено прогоном:
        /// <c>beta = 42</c> на документе без <c>beta</c> даёт 42).
        /// </summary>
        private static void EmitDeferredLocals(
            SourceBuilder builder,
            SubjectModel subject,
            IReadOnlyList<MemberModel> members
            )
        {
            foreach (var parameter in subject.Parameters)
            {
                var member = members.First(m => m.MemberName == parameter.MemberName);
                builder.Line("var " + Argument(member) + " = " + parameter.DefaultExpression + ";");
            }

            foreach (var member in members.Where(m => !m.IsConstructorParameter))
            {
                builder.Line("var " + Assigned(member) + " = default(" + member.Value.Declaration + ");");
                builder.Line("var " + Seen(member) + " = false;");
            }

            builder.Line();
        }

        private static string Construct(SubjectModel subject, IReadOnlyList<MemberModel> members)
        {
            var arguments = subject.Parameters
                .Select(p => Argument(members.First(m => m.MemberName == p.MemberName)));

            return "new " + subject.FullName + "(" + string.Join(", ", arguments) + ")";
        }

        private static string Target(MemberModel member, bool deferred)
        {
            if (!deferred)
            {
                return "result." + member.MemberName;
            }

            return member.IsConstructorParameter ? Argument(member) : Assigned(member);
        }

        //префиксы, а не голые имена члена: в теле читателя уже живут name,
        //position, context, result и локальные, которые печатает читатель
        //значения, - и совпасть с любым из них член вправе
        private static string Argument(MemberModel member) => "arg_" + member.MemberName;

        private static string Assigned(MemberModel member) => "set_" + member.MemberName;

        private static string Seen(MemberModel member) => "has_" + member.MemberName;

        /// <summary>
        /// Читатель коллекции. Отличие от объекта не только в скобках: у
        /// массива нет имён, значит нет и диспетчера, - весь цикл сводится к
        /// «прочитать элемент, проверить запятую».
        ///
        /// Массив читается в <c>T[]</c> с удвоением и подрезкой в конце, а не
        /// через <c>List&lt;T&gt;.ToArray()</c>: у второго способа ровно те же
        /// перевыделения плюс лишняя копия и лишний объект.
        /// </summary>
        /// <summary>
        /// Запись enum'а именем. Значение вне набора уходит числом - это не
        /// послабление, а поведение эталона: <c>(Named)77</c> он пишет как
        /// <c>77</c>, а не отказывает.
        /// </summary>
        private static void EmitEnumWriter(SourceBuilder builder, EnumModel enumModel, string exhauster)
        {
            builder.OpenBlock(
                "private static void WriteEnum_" + enumModel.MethodSuffix + "("
                + exhauster + " exhauster, " + enumModel.FullName + " value)"
                );

            builder.OpenBlock("switch (value)");

            foreach (var member in enumModel.Members)
            {
                builder.Line("case " + enumModel.FullName + "." + member.MemberName + ":");
                builder.Indent();
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("\"" + member.JsonName + "\"") + ");");
                builder.Line("return;");
                builder.Unindent();
                builder.Line();
            }

            builder.CloseBlock();
            builder.Line();

            builder.Line("exhauster.Append((" + BuiltinTypes.GetTypeName(enumModel.Underlying) + ")value);");

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Чтение enum'а именем. Форм на входе три, и все три законны у эталона:
        /// имя, имя в экранированном виде и число - в кавычках или без.
        ///
        /// Регистр сворачивается только у тех членов, чьё имя пришло из C#:
        /// имя из <c>[JsonStringEnumMemberName]</c> эталон принимает лишь в
        /// точности, и это проверено прогоном, а не выведено из его исходников.
        /// </summary>
        private static void EmitEnumReader(SourceBuilder builder, EnumModel enumModel, string injector)
        {
            var underlying = BuiltinTypes.GetTypeName(enumModel.Underlying);

            builder.Line("private static " + enumModel.FullName + " ReadEnum_" + enumModel.MethodSuffix + "(");
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            builder.OpenBlock(
                "if (" + Scan + ".Peek(json, ref position) == " + TokenKind + ".String)"
                );

            builder.Line("var raw = " + Scan + ".ReadStringContent(json, ref position, out var rawEscaped);");
            builder.OpenBlock("if (rawEscaped)");
            builder.Line("raw = context.UnescapeValue(raw);");
            builder.CloseBlock();
            builder.Line();

            var buckets = enumModel.Members
                .GroupBy(m => System.Text.Encoding.UTF8.GetByteCount(m.JsonName))
                .OrderBy(g => g.Key);

            builder.OpenBlock("switch (raw.Length)");

            foreach (var bucket in buckets)
            {
                builder.Line("case " + bucket.Key + ":");
                builder.OpenBlock();

                foreach (var member in bucket)
                {
                    var comparison = member.MatchExactly
                        ? "global::System.MemoryExtensions.SequenceEqual(raw, "
                            + SourceBuilder.Utf8Literal(member.JsonName) + ")"
                        : AsciiName + ".EqualsIgnoreCase(raw, " + SourceBuilder.Utf8Literal(member.JsonName) + ")";

                    builder.OpenBlock("if (" + comparison + ")");
                    builder.Line("return " + enumModel.FullName + "." + member.MemberName + ";");
                    builder.CloseBlock();
                    builder.Line();
                }

                builder.Line("break;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.CloseBlock();
            builder.Line();

            //имя не подошло - остаётся число в кавычках; не число даст отказ
            //разбора, а он и требуется
            builder.Line("injector.Parse(ref context, raw, out " + underlying + " named);");
            builder.Line("return (" + enumModel.FullName + ")named;");

            builder.CloseBlock();
            builder.Line();

            builder.Line("var rawNumber = " + Scan + ".ReadNumberRaw(json, ref position);");
            builder.Line("injector.Parse(ref context, rawNumber, out " + underlying + " number);");
            builder.Line("return (" + enumModel.FullName + ")number;");

            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitCollectionReader(SourceBuilder builder, ValueModel collection, string injector)
        {
            var isArray = collection.Form == ValueForm.Array;
            var isMap = collection.Form == ValueForm.Dictionary;
            var element = collection.Element!;

            var open = Scan + (isMap ? ".OpenBrace" : ".OpenBracket");
            var close = Scan + (isMap ? ".CloseBrace" : ".CloseBracket");

            builder.Line(
                "private static " + collection.TypeName + "? ReadCollection_" + collection.MethodSuffix + "("
                );
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            builder.OpenBlock("if (" + Scan + ".TryReadNull(json, ref position))");
            builder.Line("return null;");
            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + open + ");");
            builder.Line();

            builder.OpenBlock("if (" + Scan + ".TryConsume(json, ref position, " + close + "))");
            builder.Line(
                isArray
                    ? "return " + ValueSourceProducer.Array + ".Empty<" + element.Declaration + ">();"
                    : "return new " + collection.TypeName + "();"
                );
            builder.CloseBlock();
            builder.Line();

            if (isArray)
            {
                builder.Line("var result = new " + element.Declaration + "[4];");
                builder.Line("var count = 0;");
            }
            else
            {
                builder.Line("var result = new " + collection.TypeName + "();");
            }

            builder.Line();
            builder.OpenBlock("while (true)");

            if (isMap)
            {
                //ключ словаря приходится материализовать строкой: с именем
                //члена его не сравнить - членов тут нет, - и положить в словарь
                //спан нельзя
                builder.Line("var rawKey = " + Scan + ".ReadStringContent(json, ref position, out var keyEscaped);");
                builder.Line("injector.ParseText(ref context, rawKey, keyEscaped, out string key);");
                builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
                builder.Line();
            }

            builder.Line(element.Declaration + " item;");
            ValueSourceProducer.ReadValue(builder, element, "item");
            builder.Line();

            if (isArray)
            {
                builder.OpenBlock("if (count == result.Length)");
                builder.Line(ValueSourceProducer.Array + ".Resize(ref result, count * 2);");
                builder.CloseBlock();
                builder.Line();
                builder.Line("result[count] = item;");
                builder.Line("count++;");
            }
            else if (isMap)
            {
                //индексатор, а не Add: повторённый ключ у System.Text.Json
                //выигрывает последним вхождением, а Add бросил бы
                builder.Line("result[key] = item;");
            }
            else
            {
                builder.Line("result.Add(item);");
            }

            builder.Line();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + close + ");");

            if (isArray)
            {
                builder.OpenBlock("if (count != result.Length)");
                builder.Line(ValueSourceProducer.Array + ".Resize(ref result, count);");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line("return result;");

            builder.CloseBlock();
            builder.Line();
        }
    }
}
