using System.Collections.Generic;
using System.Linq;
using JsonGoddess.Generator.Binding;
using JsonGoddess.Generator.Model;
using JsonGoddess.Generator.Shared;

namespace JsonGoddess.Generator.Emit
{
    /// <summary>
    /// Печатает partial-часть хоста целиком.
    ///
    /// Преамбула здесь не формальность: сгенерированный код живёт в чужой
    /// сборке, и её настройки анализа - не наше дело. <c>&lt;auto-generated/&gt;</c>
    /// плюс общее подавление предупреждений означают, что подключение
    /// JsonGoddess не может испортить чужую сборку с
    /// <c>TreatWarningsAsErrors</c>.
    /// </summary>
    public static class ClassSourceProducer
    {
        private const string Scan = ValueSourceProducer.Scan;
        private const string Mem = ValueSourceProducer.Mem;
        private const string TokenKind = "global::JsonGoddess.Internal.JsonTokenKind";
        private const string AsciiName = "global::JsonGoddess.Internal.JsonAsciiName";
        private const string Context = "global::JsonGoddess.JsonParseContext";
        private const string Span = "global::System.ReadOnlySpan<byte>";
        private const string EqualityComparer = "global::System.Collections.Generic.EqualityComparer";
        private const string DocumentException = "global::JsonGoddess.JsonDocumentException";

        /// <summary>
        /// Просьба к JIT'у вставить тело по месту. Ставится только на читатель
        /// скаляра, и стоит она 810 байт на графе из двухсот типов.
        ///
        /// Обоснование у неё узкое, и назвать его надо точно (§16.2 плана). В
        /// <b>рукописном</b> читателе WIDE вызов читателя скаляра не стоит
        /// ничего и без атрибута: три формы - скаляр по месту, скаляр вызовом,
        /// скаляр вызовом с атрибутом - в одном round-robin различаются на
        /// проценты при разбросе того же порядка, то есть JIT там встраивает
        /// сам. В <b>порождённом</b> читателе метод больше - гибридный
        /// диспетчер плюс путь разэкранирования, - и отставание от лучшей
        /// рукописной формы, померенное внутри каждого прогона, выходит 0.6%
        /// (REGULAR) и 2.4% (WIDE) с атрибутом против 2.2% и 6.4% без него.
        /// </summary>
        private const string Inline =
            "[global::System.Runtime.CompilerServices.MethodImpl("
            + "global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";

        public static string Produce(HostModel host)
        {
            var builder = new SourceBuilder();

            builder.Line("// <auto-generated/>");
            builder.Line("#pragma warning disable");
            builder.Line("#nullable enable");
            builder.Line();

            EmitAliases(builder);

            //namespace файловой области, а не блоком: она снимает один уровень
            //отступа со всего файла, а на графе из двухсот типов отступы - это
            //треть его объёма (§16.2 плана). C# 10 для неё достаточно, а у нас
            //и без того требуется одиннадцатый - из-за u8-литералов.
            if (!string.IsNullOrEmpty(host.Namespace))
            {
                builder.Line("namespace " + host.Namespace + ";");
                builder.Line();
            }

            builder.OpenBlock(host.TypeName);

            foreach (var exhauster in host.ExhausterTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitSerializeEntry(builder, subject, exhauster);
                    }

                    if (subject.IsPolymorphic)
                    {
                        EmitPolymorphicWriter(builder, host, subject, exhauster, host.DictionaryKeyNaming);
                    }
                    else
                    {
                        EmitWriter(
                            builder, subject, exhauster, host.DictionaryKeyNaming,
                            "Write_" + subject.MethodSuffix, null
                            );
                    }
                }

                foreach (var collection in host.Collections)
                {
                    EmitCollectionWriter(builder, collection, exhauster, host.DictionaryKeyNaming);
                }

                foreach (var enumModel in host.StringEnums)
                {
                    EmitEnumWriter(builder, enumModel, exhauster);
                }
            }

            foreach (var injector in host.InjectorTypes)
            {
                foreach (var subject in host.Subjects)
                {
                    if (subject.IsRoot)
                    {
                        EmitDeserializeEntry(builder, subject, injector);
                    }

                    EmitReader(
                        builder, subject, injector, null,
                        subject.IsPolymorphic ? subject.DiscriminatorName : null
                        );

                    foreach (var derived in subject.Derived)
                    {
                        EmitReader(
                            builder,
                            host.Subjects.First(s => s.FullName == derived.FullName),
                            injector,
                            PairReaderName(subject, derived),
                            subject.DiscriminatorName
                            );
                    }
                }

                foreach (var scalar in host.Scalars)
                {
                    EmitScalarReader(builder, scalar, injector);
                }

                foreach (var collection in host.Collections)
                {
                    EmitCollectionReader(builder, collection, injector);
                }

                foreach (var enumModel in host.StringEnums)
                {
                    EmitEnumReader(builder, enumModel, injector);
                }
            }

            builder.CloseBlock();

            return builder.ToString();
        }

        /// <summary>
        /// Псевдонимы вместо полных имён.
        ///
        /// <c>global::JsonGoddess.Internal.JsonScan</c> встречается в
        /// порождённом коде чаще всего остального вместе взятого, и на графе
        /// из двухсот типов одно это имя занимало 164 килобайта из 1.9
        /// мегабайта (§16.2 плана). Псевдоним - то же самое связывание, но
        /// один раз.
        /// </summary>
        /// <remarks>
        /// Имена с двумя подчёркиваниями - не кокетство. Псевдоним уровня
        /// файла проигрывает типу, объявленному в том же namespace, что и
        /// хост: назови мы его <c>Scan</c>, чужой <c>Scan</c> рядом с хостом
        /// молча перехватил бы связывание. С <c>__</c> такого типа не бывает,
        /// а если он всё же найдётся, это будет ошибка компиляции, а не другое
        /// поведение.
        /// </remarks>
        private static void EmitAliases(SourceBuilder builder)
        {
            builder.Line("using " + Scan + " = " + ValueSourceProducer.ScanFullName + ";");
            builder.Line("using " + Mem + " = " + ValueSourceProducer.MemoryExtensionsFullName + ";");
            builder.Line();
        }

        private static void EmitSerializeEntry(SourceBuilder builder, SubjectModel subject, string exhauster)
        {
            builder.OpenBlock(
                "public static void Serialize(" + exhauster + " exhauster, " + subject.Declaration + " value)"
                );
            builder.Line("Write_" + subject.MethodSuffix + "(exhauster, value);");
            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitDeserializeEntry(SourceBuilder builder, SubjectModel subject, string injector)
        {
            builder.OpenBlock(
                "public static void Deserialize(" + injector + " injector, " + Span + " json, out "
                + subject.Declaration + " result)"
                );
            builder.Line("var position = 0;");
            builder.Line("var context = new " + Context + "(json);");

            //try/finally здесь стоит один раз на документ, а не на член:
            //контекст арендует буфер только если в документе попалось
            //экранированное имя, но вернуть арендованное надо в любом случае
            builder.OpenBlock("try");
            builder.Line("result = Read_" + subject.MethodSuffix + "(injector, json, ref position, ref context);");
            builder.CloseBlock();
            builder.OpenBlock("finally");
            builder.Line("context.Release();");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Запись. Разделители склеены с именами свойств в один
        /// UTF-8-литерал: структура документа известна на этапе компиляции, и
        /// автомата состояний, стека глубины и проверки "нужна ли запятая"
        /// здесь нет вовсе - в отличие от <c>Utf8JsonWriter</c>, который не
        /// знает, что ему напишут следующим.
        ///
        /// Ни одной ветки на разделители в фазе 2 не бывает и по второй
        /// причине: условно опускаемых членов ещё нет, поэтому запятые
        /// безусловны.
        /// </summary>
        /// <summary>
        /// Писатель полиморфной базы: развилка по <b>точному</b> типу значения.
        ///
        /// Не <c>is</c>, и это не стилистика. Незарегистрированный потомок
        /// зарегистрированного потомка (<c>Poodle : Dog</c>) у эталона -
        /// <c>NotSupportedException</c>, а <c>is Dog</c> записал бы его как
        /// <c>Dog</c>, потеряв половину членов и не сказав об этом.
        ///
        /// Дальше по методу на пару «база + производный»: значение
        /// дискриминатора принадлежит паре, а тело у пары своё, потому что
        /// дискриминатор склеивается со скобкой и именем первого члена в один
        /// литерал - ровно как всё остальное строение документа.
        /// </summary>
        private static void EmitPolymorphicWriter(
            SourceBuilder builder,
            HostModel host,
            SubjectModel subject,
            string exhauster,
            JsonNamingStyle keyNaming
            )
        {
            var selfIsDerived = subject.Derived.Any(d => d.FullName == subject.FullName);

            builder.OpenBlock(
                "private static void Write_" + subject.MethodSuffix + "("
                + exhauster + " exhauster, " + subject.Declaration + " value)"
                );

            builder.OpenBlock("if (value is null)");
            builder.Line("exhauster.AppendNull();");
            builder.Line("return;");
            builder.CloseBlock();
            builder.Line();

            builder.Line("var runtimeType = value.GetType();");
            builder.Line();

            foreach (var derived in subject.Derived)
            {
                builder.OpenBlock("if (runtimeType == typeof(" + derived.FullName + "))");
                builder.Line(
                    PairWriterName(subject, derived) + "(exhauster, (" + derived.FullName + ")value);"
                    );
                builder.Line("return;");
                builder.CloseBlock();
                builder.Line();
            }

            if (selfIsDerived)
            {
                //сам тип уже разобран веткой выше, значит сюда доезжает только
                //то, чего в списке нет
                builder.Line("throw " + Unsupported(subject) + ";");
            }
            else
            {
                builder.OpenBlock("if (runtimeType != typeof(" + subject.FullName + "))");
                builder.Line("throw " + Unsupported(subject) + ";");
                builder.CloseBlock();
                builder.Line();
                builder.Line("WriteSelf_" + subject.MethodSuffix + "(exhauster, value);");
            }

            builder.CloseBlock();
            builder.Line();

            if (!selfIsDerived)
            {
                //база без собственного дискриминатора пишется как обычный
                //объект - проверено прогоном: у эталона он появляется только
                //тогда, когда база объявлена производной от самой себя
                EmitWriter(
                    builder, subject, exhauster, keyNaming, "WriteSelf_" + subject.MethodSuffix, null
                    );
            }

            foreach (var derived in subject.Derived)
            {
                EmitWriter(
                    builder,
                    host.Subjects.First(s => s.FullName == derived.FullName),
                    exhauster,
                    keyNaming,
                    PairWriterName(subject, derived),
                    derived.DiscriminatorLiteral is null
                        ? null
                        : "\"" + subject.DiscriminatorName + "\":" + derived.DiscriminatorLiteral
                    );
            }
        }

        private static string PairWriterName(SubjectModel subject, DerivedTypeModel derived) =>
            "Write_" + derived.MethodSuffix + "_As_" + subject.MethodSuffix;

        private static string PairReaderName(SubjectModel subject, DerivedTypeModel derived) =>
            "ReadBody_" + derived.MethodSuffix + "_As_" + subject.MethodSuffix;

        private static string Unsupported(SubjectModel subject)
        {
            return "new global::System.NotSupportedException(\"runtime type \" + runtimeType + "
                + "\" is not supported by polymorphic type '" + subject.FullName.Replace("global::", string.Empty)
                + "'\")";
        }

        private static void EmitWriter(
            SourceBuilder builder,
            SubjectModel subject,
            string exhauster,
            JsonNamingStyle keyNaming,
            string methodName,
            string? discriminator
            )
        {
            var members = subject.Members.Where(m => m.CanWrite).ToList();

            builder.OpenBlock(
                "private static void " + methodName + "("
                + exhauster + " exhauster, " + subject.Declaration + " value)"
                );

            //у структуры проверки нет, и это не экономия ветки: значение
            //структуры null описать не может, а Nullable<> над ней разбирается
            //на месте члена, до вызова
            if (!subject.IsValueType)
            {
                builder.OpenBlock("if (value is null)");
                builder.Line("exhauster.AppendNull();");
                builder.Line("return;");
                builder.CloseBlock();
                builder.Line();
            }

            //Субъект, который сам является коллекцией (§9.10 плана): у него
            //нет обычных членов вовсе (members здесь и так пуст), а тело -
            //цикл по элементам. Проверка стоит раньше "members.Count == 0",
            //иначе такой субъект уехал бы как "{}" - ветка ниже про пустой
            //объект, а не про пустую коллекцию.
            if (subject.CollectionShape is not null)
            {
                EmitCollectionSubjectWriterBody(builder, subject, keyNaming);
                builder.CloseBlock();
                builder.Line();
                return;
            }

            if (members.Count == 0)
            {
                builder.Line(
                    "exhauster.AppendRaw("
                    + SourceBuilder.Utf8Literal(discriminator is null ? "{}" : "{" + discriminator + "}")
                    + ");"
                    );
                builder.CloseBlock();
                builder.Line();
                return;
            }

            //Состояние на этапе компиляции, а не в рантайме. pendingOpen -
            //фигурная скобка ещё не напечатана и склеится с именем первого
            //члена; commaIsCertain - до этого места точно что-то написано, и
            //запятая снова становится частью литерала.
            var pendingOpen = true;
            var commaIsCertain = false;
            var needCommaDeclared = false;

            //дискриминатор печатается первым свойством - так его пишет эталон,
            //и так же он его требует на чтении. Для автомата состояний это
            //означает, что скобка уже напечатана и запятая перед следующим
            //членом заведомо нужна
            if (discriminator is not null)
            {
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{" + discriminator) + ");");
                pendingOpen = false;
                commaIsCertain = true;
            }

            for (var i = 0; i < members.Count; i++)
            {
                var member = members[i];

                if (member.Condition == WriteCondition.Always)
                {
                    //скобка склеивается с именем первого члена только здесь: у
                    //условного члена она обязана быть напечатана снаружи его
                    //ветки, иначе объект без членов остался бы без скобки
                    var literal = (pendingOpen ? "{" : commaIsCertain ? "," : string.Empty)
                        + "\"" + member.JsonName + "\":";

                    if (!pendingOpen && !commaIsCertain && needCommaDeclared)
                    {
                        builder.OpenBlock("if (needComma)");
                        builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(",") + ");");
                        builder.CloseBlock();
                        builder.Line();
                    }

                    builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(literal) + ");");
                    ValueSourceProducer.WriteValue(builder, member.Value, "value." + member.MemberName, keyNaming);

                    pendingOpen = false;
                    commaIsCertain = true;
                    continue;
                }

                if (pendingOpen)
                {
                    builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{") + ");");
                    pendingOpen = false;
                }

                if (!commaIsCertain && !needCommaDeclared)
                {
                    builder.Line("var needComma = false;");
                    needCommaDeclared = true;
                }

                builder.Line();

                var candidate = "candidate" + i;
                var conditionalLiteral = (commaIsCertain ? "," : string.Empty)
                    + "\"" + member.JsonName + "\":";

                builder.OpenBlock();
                builder.Line("var " + candidate + " = value." + member.MemberName + ";");
                builder.OpenBlock("if (" + Condition(member, candidate) + ")");

                if (!commaIsCertain)
                {
                    //у самого первого члена needComma заведомо false, и ветка
                    //здесь была бы веткой ради симметрии
                    if (i > 0)
                    {
                        builder.OpenBlock("if (needComma)");
                        builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(",") + ");");
                        builder.CloseBlock();
                        builder.Line();
                    }

                    builder.Line("needComma = true;");
                }

                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(conditionalLiteral) + ");");
                ValueSourceProducer.WriteValue(builder, member.Value, candidate, keyNaming);

                builder.CloseBlock();
                builder.CloseBlock();
                builder.Line();
            }

            if (pendingOpen)
            {
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("{") + ");");
            }

            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("}") + ");");
            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Условие записи. Для <c>default</c> сравнение печатается прямое, а не
        /// через <c>EqualityComparer&lt;T&gt;.Default</c>: тип известен, и на
        /// всех обслуживаемых типах <c>!=</c> даёт тот же ответ - включая
        /// <c>-0.0</c>, который эталон тоже опускает.
        /// </summary>
        private static string Condition(MemberModel member, string candidate)
        {
            if (member.Condition == WriteCondition.WhenNotNull || member.Value.IsNullable)
            {
                return candidate + " is not null";
            }

            //Структура-субъект: у неё нет operator !=, и печатать сравнение
            //значило бы выдать код, который не компилируется. Эталон в этом
            //месте сравнивает через EqualityComparer<T>.Default - проверено
            //прогоном: структура в значении по умолчанию из документа
            //исчезает, - и цена его вызова тут уместна, потому что платит за
            //неё тот, кто явно написал WhenWritingDefault на структуре.
            if (member.Value.IsValueType)
            {
                return "!" + EqualityComparer + "<" + member.Value.TypeName + ">.Default.Equals("
                    + candidate + ", default(" + member.Value.TypeName + "))";
            }

            return candidate + " != default(" + member.Value.TypeName + ")";
        }

        /// <summary>
        /// Развилка по дискриминатору - <b>только первым свойством</b>.
        ///
        /// Это не наше упрощение, а требование эталона: документ, в котором
        /// <c>$type</c> стои́т не первым, он читать отказывается
        /// (<c>JsonException</c>), и принять такой документ значило бы прочесть
        /// то, чего он не читает.
        ///
        /// Значение дискриминатора сравнивается <b>сырым текстом</b>, вместе с
        /// кавычками, если они есть. Одна ветка на строку и на число вместо
        /// двух: <c>"dog"</c> и <c>7</c> различаются как байты и без разбора
        /// лексемы.
        /// </summary>
        private static void EmitDiscriminatorDispatch(SourceBuilder builder, SubjectModel subject)
        {
            builder.Line("var discriminatorStart = position;");
            builder.Line("var hasDiscriminator = false;");
            builder.Line();

            builder.OpenBlock("if (" + Scan + ".Peek(json, ref position) == " + TokenKind + ".String)");
            builder.Line("var firstName = " + Scan + ".ReadStringContent(json, ref position, out var firstEscaped);");
            builder.OpenBlock("if (firstEscaped)");
            builder.Line("firstName = context.UnescapeName(firstName);");
            builder.CloseBlock();
            builder.Line();
            builder.Line(
                "hasDiscriminator = " + Mem + ".SequenceEqual(firstName, "
                + SourceBuilder.Utf8Literal(subject.DiscriminatorName) + ");"
                );
            builder.CloseBlock();
            builder.Line();

            builder.OpenBlock("if (hasDiscriminator)");
            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
            builder.Line(Scan + ".SkipWhitespace(json, ref position);");
            builder.Line("var valueStart = position;");
            builder.Line(Scan + ".SkipValue(json, ref position);");
            builder.Line("var discriminator = json.Slice(valueStart, position - valueStart);");
            builder.Line();

            foreach (var derived in subject.Derived)
            {
                if (derived.DiscriminatorLiteral is null)
                {
                    //[JsonDerivedType(typeof(D))] без значения: эталон такой тип
                    //пишет без дискриминатора, значит и прочитать его обратно
                    //производным не по чему - у него просто нет имени
                    continue;
                }

                builder.OpenBlock(
                    "if (" + Mem + ".SequenceEqual(discriminator, "
                    + SourceBuilder.Utf8Literal(derived.DiscriminatorLiteral) + "))"
                    );
                builder.Line(
                    "return " + PairReaderName(subject, derived)
                    + "(injector, json, ref position, ref context);"
                    );
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line(
                "throw new " + DocumentException + "(\"unrecognized type discriminator for '"
                + subject.FullName.Replace("global::", string.Empty) + "'\", valueStart);"
                );
            builder.CloseBlock();
            builder.Line();

            builder.Line("position = discriminatorStart;");
            builder.Line();
        }

        /// <summary>
        /// Читатель субъекта.
        /// </summary>
        /// <param name="bodyName">
        /// Не <c>null</c> - печатается <b>тело</b>: читатель, которого позвали
        /// уже внутри объекта, сразу после значения дискриминатора. Скобку и
        /// <c>null</c> разобрал звавший, и первое, что здесь бывает, - запятая
        /// или закрывающая скобка.
        ///
        /// Своя копия тела, а не разделение с обычным читателем: разделить их
        /// значило бы добавить вызов на каждое чтение каждого объекта ради
        /// экономии текста у полиморфных типов.
        /// </param>
        private static void EmitReader(
            SourceBuilder builder,
            SubjectModel subject,
            string injector,
            string? bodyName,
            string? discriminatorGuard = null
            )
        {
            var members = subject.Members.Where(m => m.CanRead).ToList();
            var body = bodyName is not null;

            builder.Line(
                "private static " + subject.Declaration + " "
                + (bodyName ?? "Read_" + subject.MethodSuffix) + "("
                );
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            //У структуры ветки на null нет, и это тоже не экономия: null на
            //месте структуры обязан кончиться отказом - ровно так ведёт себя
            //эталон, - и он кончается им сам, на Expect(OpenBrace) ниже.
            //Nullable<> над структурой разбирается на месте члена, до вызова.
            if (!body && !subject.IsValueType)
            {
                builder.OpenBlock("if (" + Scan + ".TryReadNull(json, ref position))");
                builder.Line("return null;");
                builder.CloseBlock();
                builder.Line();
            }

            //Субъект-коллекция (§9.10) не полиморфен (связыватель отказывает
            //на этой комбинации), значит body здесь всегда null, и метод
            //целиком печатается этой веткой - без диспетчера имён, без
            //отложенной сборки: строить нечем, кроме конструктора без
            //параметров, а класть - только в саму коллекцию.
            if (subject.CollectionShape is not null)
            {
                EmitCollectionSubjectReaderBody(builder, subject);
                builder.CloseBlock();
                builder.Line();
                return;
            }

            if (!body)
            {
                builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".OpenBrace);");
            }

            var deferred = subject.NeedsDeferredConstruction;

            if (deferred)
            {
                EmitDeferredLocals(builder, subject, members);
            }
            else
            {
                builder.Line("var result = new " + subject.FullName + "();");
                builder.Line();
            }

            if (subject.IsPolymorphic && !body)
            {
                EmitDiscriminatorDispatch(builder, subject);
            }

            builder.OpenBlock(
                body
                    ? "if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))"
                    : "if (" + Scan + ".TryConsume(json, ref position, " + Scan + ".CloseBrace))"
                );

            if (body)
            {
                builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".CloseBrace);");
            }

            builder.Line(deferred ? "return " + Construct(subject, members) + ";" : "return result;");
            builder.CloseBlock();
            builder.Line();

            builder.OpenBlock("while (true)");

            builder.Line("var name = " + Scan + ".ReadStringContent(json, ref position, out var nameEscaped);");
            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
            builder.Line();

            if (members.Count > 0)
            {
                builder.Unindent();
                builder.Line("dispatch:");
                builder.Indent();

                //Дискриминатор, встреченный не первым свойством, - отказ.
                //Эталон здесь отказывает тоже, и принять такой документ
                //значило бы прочесть то, чего не читает он. Проверка стои́т
                //после ярлыка, чтобы сработать и на разэкранированном имени.
                if (discriminatorGuard is not null)
                {
                    builder.OpenBlock(
                        "if (" + Mem + ".SequenceEqual(name, "
                        + SourceBuilder.Utf8Literal(discriminatorGuard) + "))"
                        );
                    builder.Line(
                        "throw new " + DocumentException
                        + "(\"the type discriminator must be the first property\", position);"
                        );
                    builder.CloseBlock();
                    builder.Line();
                }

                NameDispatcher.Emit(
                    builder,
                    members,
                    member =>
                    {
                        ValueSourceProducer.ReadValue(builder, member.Value, Target(member, deferred));

                        if (deferred && !member.IsConstructorParameter)
                        {
                            builder.Line(Seen(member) + " = true;");
                        }
                    }
                    );

                //Экранированное имя не совпадёт ни с одним литералом, потому
                //что литералы печатаются из имён, которым escape не нужен.
                //Значит управление доходит сюда само, и разэкранирование
                //оказывается ровно там, где оно и должно быть: на пути, по
                //которому обычный документ не идёт ни разу. Член, который
                //нашёлся, ушёл по goto раньше.
                //
                //Второй заход в тот же switch, а не второй switch: копия
                //диспетчера удвоила бы объём порождаемого кода ради случая,
                //который почти не встречается.
                builder.OpenBlock("if (nameEscaped)");
                builder.Line("nameEscaped = false;");
                builder.Line("name = context.UnescapeName(name);");
                builder.Line("goto dispatch;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line(Scan + ".SkipValue(json, ref position);");
            builder.Line();

            builder.Unindent();
            builder.Line("next:");
            builder.Indent();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".CloseBrace);");

            if (deferred)
            {
                builder.Line();
                builder.Line("var result = " + Construct(subject, members) + ";");

                foreach (var member in members.Where(m => !m.IsConstructorParameter))
                {
                    builder.OpenBlock("if (" + Seen(member) + ")");
                    builder.Line("result." + member.MemberName + " = " + Assigned(member) + ";");
                    builder.CloseBlock();
                }
            }

            builder.Line("return result;");

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Локальные отложенной формы: по одной на каждый читаемый член, плюс
        /// флаг присутствия на тех, кого присваивает не конструктор.
        ///
        /// Аргумент заводится <b>объявленным умолчанием параметра</b>, и это
        /// заменяет флаг для него целиком: не было имени в документе -
        /// осталось умолчание, ровно как у эталона (проверено прогоном:
        /// <c>beta = 42</c> на документе без <c>beta</c> даёт 42).
        /// </summary>
        private static void EmitDeferredLocals(
            SourceBuilder builder,
            SubjectModel subject,
            IReadOnlyList<MemberModel> members
            )
        {
            foreach (var parameter in subject.Parameters)
            {
                var member = members.First(m => m.MemberName == parameter.MemberName);
                builder.Line("var " + Argument(member) + " = " + parameter.DefaultExpression + ";");
            }

            foreach (var member in members.Where(m => !m.IsConstructorParameter))
            {
                builder.Line("var " + Assigned(member) + " = default(" + member.Value.Declaration + ");");
                builder.Line("var " + Seen(member) + " = false;");
            }

            builder.Line();
        }

        private static string Construct(SubjectModel subject, IReadOnlyList<MemberModel> members)
        {
            var arguments = subject.Parameters
                .Select(p => Argument(members.First(m => m.MemberName == p.MemberName)));

            return "new " + subject.FullName + "(" + string.Join(", ", arguments) + ")";
        }

        private static string Target(MemberModel member, bool deferred)
        {
            if (!deferred)
            {
                return "result." + member.MemberName;
            }

            return member.IsConstructorParameter ? Argument(member) : Assigned(member);
        }

        //префиксы, а не голые имена члена: в теле читателя уже живут name,
        //position, context, result и локальные, которые печатает читатель
        //значения, - и совпасть с любым из них член вправе
        private static string Argument(MemberModel member) => "arg_" + member.MemberName;

        private static string Assigned(MemberModel member) => "set_" + member.MemberName;

        private static string Seen(MemberModel member) => "has_" + member.MemberName;

        /// <summary>
        /// Читатель коллекции. Отличие от объекта не только в скобках: у
        /// массива нет имён, значит нет и диспетчера, - весь цикл сводится к
        /// «прочитать элемент, проверить запятую».
        ///
        /// Массив читается в <c>T[]</c> с удвоением и подрезкой в конце, а не
        /// через <c>List&lt;T&gt;.ToArray()</c>: у второго способа ровно те же
        /// перевыделения плюс лишняя копия и лишний объект.
        /// </summary>
        /// <summary>
        /// Запись enum'а именем. Значение вне набора уходит числом - это не
        /// послабление, а поведение эталона: <c>(Named)77</c> он пишет как
        /// <c>77</c>, а не отказывает.
        /// </summary>
        private static void EmitEnumWriter(SourceBuilder builder, EnumModel enumModel, string exhauster)
        {
            builder.OpenBlock(
                "private static void WriteEnum_" + enumModel.MethodSuffix + "("
                + exhauster + " exhauster, " + enumModel.FullName + " value)"
                );

            builder.OpenBlock("switch (value)");

            foreach (var member in enumModel.Members)
            {
                builder.Line("case " + enumModel.FullName + "." + member.MemberName + ":");
                builder.Indent();
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal("\"" + member.JsonName + "\"") + ");");
                builder.Line("return;");
                builder.Unindent();
                builder.Line();
            }

            builder.CloseBlock();
            builder.Line();

            builder.Line("exhauster.Append((" + BuiltinTypes.GetTypeName(enumModel.Underlying) + ")value);");

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Чтение enum'а именем. Форм на входе три, и все три законны у эталона:
        /// имя, имя в экранированном виде и число - в кавычках или без.
        ///
        /// Регистр сворачивается только у тех членов, чьё имя пришло из C#:
        /// имя из <c>[JsonStringEnumMemberName]</c> эталон принимает лишь в
        /// точности, и это проверено прогоном, а не выведено из его исходников.
        /// </summary>
        private static void EmitEnumReader(SourceBuilder builder, EnumModel enumModel, string injector)
        {
            var underlying = BuiltinTypes.GetTypeName(enumModel.Underlying);

            builder.Line("private static " + enumModel.FullName + " ReadEnum_" + enumModel.MethodSuffix + "(");
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            builder.OpenBlock(
                "if (" + Scan + ".Peek(json, ref position) == " + TokenKind + ".String)"
                );

            builder.Line("var raw = " + Scan + ".ReadStringContent(json, ref position, out var rawEscaped);");
            builder.OpenBlock("if (rawEscaped)");
            builder.Line("raw = context.UnescapeValue(raw);");
            builder.CloseBlock();
            builder.Line();

            var buckets = enumModel.Members
                .GroupBy(m => System.Text.Encoding.UTF8.GetByteCount(m.JsonName))
                .OrderBy(g => g.Key);

            builder.OpenBlock("switch (raw.Length)");

            foreach (var bucket in buckets)
            {
                builder.Line("case " + bucket.Key + ":");
                builder.OpenBlock();

                foreach (var member in bucket)
                {
                    var comparison = member.MatchExactly
                        ? Mem + ".SequenceEqual(raw, "
                            + SourceBuilder.Utf8Literal(member.JsonName) + ")"
                        : AsciiName + ".EqualsIgnoreCase(raw, " + SourceBuilder.Utf8Literal(member.JsonName) + ")";

                    builder.OpenBlock("if (" + comparison + ")");
                    builder.Line("return " + enumModel.FullName + "." + member.MemberName + ";");
                    builder.CloseBlock();
                    builder.Line();
                }

                builder.Line("break;");
                builder.CloseBlock();
                builder.Line();
            }

            builder.CloseBlock();
            builder.Line();

            //имя не подошло - остаётся число в кавычках; не число даст отказ
            //разбора, а он и требуется
            builder.Line("injector.Parse(ref context, raw, out " + underlying + " named);");
            builder.Line("return (" + enumModel.FullName + ")named;");

            builder.CloseBlock();
            builder.Line();

            builder.Line("var rawNumber = " + Scan + ".ReadNumberRaw(json, ref position);");
            builder.Line("injector.Parse(ref context, rawNumber, out " + underlying + " number);");
            builder.Line("return (" + enumModel.FullName + ")number;");

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Читатель скаляра - метод на пару «вид плюс nullability», общий на
        /// весь хост.
        ///
        /// Печаталось это по месту, и на член приходилось три строки, а на
        /// nullable-член - девять: проверка на null, обе ветки и две локальные.
        /// Умноженное на число членов всех субъектов, это и оказалось самой
        /// крупной повторяющейся частью читателя (§16.2 плана). Сигнатура та
        /// же, что у читателя коллекции и субъекта, - к ветке диспетчера
        /// сводится одно присваивание.
        /// </summary>
        private static void EmitScalarReader(SourceBuilder builder, ValueModel scalar, string injector)
        {
            builder.Line(Inline);
            builder.Line(
                "private static " + scalar.Declaration + " ReadScalar_" + scalar.MethodSuffix + "("
                );
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            ValueSourceProducer.ReadScalarBody(builder, scalar);

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Писатель коллекции - метод, а не код по месту.
        ///
        /// Раньше цикл печатался в каждом члене, и обоснование стояло прямое:
        /// «выносить его в метод значило бы добавить вызов ради экономии,
        /// которой нет». Экономия померена (§16.2 плана): на графе из двухсот
        /// типов тело коллекции занимало три четверти всего писателя, потому
        /// что один и тот же <c>Dictionary&lt;string,int&gt;</c> печатался
        /// двести раз подряд. Список коллекций уже собран - его печатает
        /// читатель, - так что метод берётся из того же списка, и обе стороны
        /// стали симметричны.
        /// </summary>
        private static void EmitCollectionWriter(
            SourceBuilder builder,
            ValueModel collection,
            string exhauster,
            JsonNamingStyle keyNaming
            )
        {
            builder.OpenBlock(
                "private static void WriteCollection_" + collection.MethodSuffix + "("
                + exhauster + " exhauster, " + collection.TypeName + "? items)"
                );

            ValueSourceProducer.WriteCollectionBody(builder, collection, keyNaming);

            builder.CloseBlock();
            builder.Line();
        }

        /// <summary>
        /// Тело писателя субъекта-коллекции (§9.10 плана). Параметр уже
        /// объявлен сигнатурой обычного писателя субъекта - <c>value</c>, а не
        /// <c>items</c>, - поэтому тело печатается своей копией цикла, а не
        /// вызовом <see cref="ValueSourceProducer.WriteCollectionBody"/>: та
        /// сама печатает проверку на <c>null</c> перед собой, а здесь она уже
        /// напечатана снаружи (и не печатается вовсе для структуры).
        /// </summary>
        private static void EmitCollectionSubjectWriterBody(
            SourceBuilder builder,
            SubjectModel subject,
            JsonNamingStyle keyNaming
            )
        {
            var shape = subject.CollectionShape!;
            var isDictionary = shape.IsDictionary;

            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(isDictionary ? "{" : "[") + ");");
            builder.Line("var i = 0;");
            builder.OpenBlock("foreach (var " + (isDictionary ? "pair" : "element") + " in value)");

            builder.OpenBlock("if (i > 0)");
            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(",") + ");");
            builder.CloseBlock();
            builder.Line();
            builder.Line("i++;");

            if (isDictionary)
            {
                builder.Line("exhauster.Append(" + ValueSourceProducer.Key("pair.Key", keyNaming) + ");");
                builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(":") + ");");
                ValueSourceProducer.WriteValue(builder, shape.Element, "pair.Value", keyNaming);
            }
            else
            {
                ValueSourceProducer.WriteValue(builder, shape.Element, "element", keyNaming);
            }

            builder.CloseBlock();
            builder.Line();
            builder.Line("exhauster.AppendRaw(" + SourceBuilder.Utf8Literal(isDictionary ? "}" : "]") + ");");
        }

        /// <summary>
        /// Тело читателя субъекта-коллекции (§9.10 плана). Элемент кладётся в
        /// уже построенный <c>result</c> через явное приведение к интерфейсу
        /// (<c>ICollection&lt;T&gt;</c>/<c>IDictionary&lt;string,V&gt;</c>), а
        /// не напрямую: субъект мог реализовать интерфейс явно (без открытого
        /// метода на самом себе), и приведение работает в обоих случаях
        /// одинаково, тогда как прямой вызов - только в одном.
        /// </summary>
        private static void EmitCollectionSubjectReaderBody(SourceBuilder builder, SubjectModel subject)
        {
            var shape = subject.CollectionShape!;
            var element = shape.Element;

            var open = Scan + (shape.IsDictionary ? ".OpenBrace" : ".OpenBracket");
            var close = Scan + (shape.IsDictionary ? ".CloseBrace" : ".CloseBracket");

            builder.Line(Scan + ".Expect(json, ref position, " + open + ");");
            builder.Line();

            builder.OpenBlock("if (" + Scan + ".TryConsume(json, ref position, " + close + "))");
            builder.Line("return new " + subject.FullName + "();");
            builder.CloseBlock();
            builder.Line();

            builder.Line("var result = new " + subject.FullName + "();");
            builder.Line();
            builder.OpenBlock("while (true)");

            if (shape.IsDictionary)
            {
                //ключ приходится материализовать строкой - положить спан в
                //чужую реализацию IDictionary<string,V> нечем
                builder.Line("var rawKey = " + Scan + ".ReadStringContent(json, ref position, out var keyEscaped);");
                builder.Line("injector.ParseText(ref context, rawKey, keyEscaped, out string key);");
                builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
                builder.Line();
            }

            builder.Line(element.Declaration + " item;");
            ValueSourceProducer.ReadValue(builder, element, "item");
            builder.Line();

            builder.Line(
                shape.IsDictionary
                    ? "((global::System.Collections.Generic.IDictionary<string, " + element.Declaration
                        + ">)result)[key] = item;"
                    : "((global::System.Collections.Generic.ICollection<" + element.Declaration + ">)result).Add(item);"
                );

            builder.Line();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + close + ");");
            builder.Line("return result;");
        }

        private static void EmitCollectionReader(SourceBuilder builder, ValueModel collection, string injector)
        {
            var isArray = collection.Form == ValueForm.Array;
            var isMap = collection.Form == ValueForm.Dictionary;
            var element = collection.Element!;

            var open = Scan + (isMap ? ".OpenBrace" : ".OpenBracket");
            var close = Scan + (isMap ? ".CloseBrace" : ".CloseBracket");

            builder.Line(
                "private static " + collection.TypeName + "? ReadCollection_" + collection.MethodSuffix + "("
                );
            builder.Indent();
            builder.Line(injector + " injector,");
            builder.Line("scoped " + Span + " json,");
            builder.Line("scoped ref int position,");
            builder.Line("scoped ref " + Context + " context");
            builder.Line(")");
            builder.Unindent();
            builder.OpenBlock();

            builder.OpenBlock("if (" + Scan + ".TryReadNull(json, ref position))");
            builder.Line("return null;");
            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + open + ");");
            builder.Line();

            builder.OpenBlock("if (" + Scan + ".TryConsume(json, ref position, " + close + "))");
            builder.Line(
                isArray
                    ? "return " + ValueSourceProducer.Array + ".Empty<" + element.Declaration + ">();"
                    : "return new " + collection.ConstructTypeName + "();"
                );
            builder.CloseBlock();
            builder.Line();

            if (isArray)
            {
                builder.Line("var result = new " + element.Declaration + "[4];");
                builder.Line("var count = 0;");
            }
            else
            {
                //ConstructTypeName - конкретный тип (List<T>/Dictionary<string,V>),
                //а не объявленный: для List<T>/Dictionary<string,V> самих по
                //себе это одно и то же, а для интерфейсов на месте члена
                //(фаза 6, §9.10) строить нечем, кроме конкретного - ровно то,
                //что подставляет и сам эталон. var ниже забирает этот
                //конкретный тип, и возврат как объявленный (интерфейс)
                //происходит неявным приведением на return result.
                builder.Line("var result = new " + collection.ConstructTypeName + "();");
            }

            builder.Line();
            builder.OpenBlock("while (true)");

            if (isMap)
            {
                //ключ словаря приходится материализовать строкой: с именем
                //члена его не сравнить - членов тут нет, - и положить в словарь
                //спан нельзя
                builder.Line("var rawKey = " + Scan + ".ReadStringContent(json, ref position, out var keyEscaped);");
                builder.Line("injector.ParseText(ref context, rawKey, keyEscaped, out string key);");
                builder.Line(Scan + ".Expect(json, ref position, " + Scan + ".Colon);");
                builder.Line();
            }

            builder.Line(element.Declaration + " item;");
            ValueSourceProducer.ReadValue(builder, element, "item");
            builder.Line();

            if (isArray)
            {
                builder.OpenBlock("if (count == result.Length)");
                builder.Line(ValueSourceProducer.Array + ".Resize(ref result, count * 2);");
                builder.CloseBlock();
                builder.Line();
                builder.Line("result[count] = item;");
                builder.Line("count++;");
            }
            else if (isMap)
            {
                //индексатор, а не Add: повторённый ключ у System.Text.Json
                //выигрывает последним вхождением, а Add бросил бы
                builder.Line("result[key] = item;");
            }
            else
            {
                builder.Line("result.Add(item);");
            }

            builder.Line();
            builder.OpenBlock("if (!" + Scan + ".TryConsume(json, ref position, " + Scan + ".Comma))");
            builder.Line("break;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();

            builder.Line(Scan + ".Expect(json, ref position, " + close + ");");

            if (isArray)
            {
                builder.OpenBlock("if (count != result.Length)");
                builder.Line(ValueSourceProducer.Array + ".Resize(ref result, count);");
                builder.CloseBlock();
                builder.Line();
            }

            builder.Line("return result;");

            builder.CloseBlock();
            builder.Line();
        }
    }
}
