using System.Collections.Generic;
using System.Linq;
using JsonGoddess.Generator.Binding;
using JsonGoddess.Generator.Model;

namespace JsonGoddess.Generator.Emit
{
    /// <summary>
    /// Входной форматтер ASP.NET Core MVC (PLAN.md §12.9, фаза 10, пункт 6г) -
    /// печатаемый <b>в сборку потребителя</b>, где ссылка на ASP.NET Core уже
    /// есть. Третий пакет для этого не нужен: его единственным содержимым был бы
    /// этот файл.
    ///
    /// <para>
    /// Печатается от <b>веб-профиля моста</b>, и это не удобство расположения:
    /// у того набор стражей подтянут к эталону (<c>CompatGuards</c>). Форматтер
    /// от хоста с другим набором принимал бы запросом документы, которых не
    /// принимает <c>System.Text.Json</c>, - найдено пунктом 6б на
    /// <c>[{"id":01}]</c>.
    /// </para>
    ///
    /// <para>
    /// <b>Регистрируется руками, одной строкой.</b> Мост подменяет реализацию
    /// внутри машинерии эталона и потому включается сам; форматтер - это
    /// изменение конвейера приложения, видимое всем его контроллерам. Такое
    /// не делают за человека молча, даже когда умеют. Печатается расширение
    /// <c>AddJsonGoddess()</c>, и одна строка в <c>Program.cs</c> - вся цена.
    /// </para>
    /// </summary>
    public static class StreamingFormatterProducer
    {
        public const string FormatterTypeName = "JsonGoddessStreamingInputFormatter";

        public const string ExtensionsTypeName = "JsonGoddessStreamingExtensions";

        private const string DocumentException = "global::JsonGoddess.JsonDocumentException";
        private const string Injector = "global::JsonGoddess.DefaultInjector";
        private const string InputFormatter = "global::Microsoft.AspNetCore.Mvc.Formatters.InputFormatter";
        private const string FormatterContext = "global::Microsoft.AspNetCore.Mvc.Formatters.InputFormatterContext";
        private const string FormatterResult = "global::Microsoft.AspNetCore.Mvc.Formatters.InputFormatterResult";
        private const string MvcOptions = "global::Microsoft.AspNetCore.Mvc.MvcOptions";
        private const string List = "global::System.Collections.Generic.List";
        private const string Task = "global::System.Threading.Tasks.Task";

        public static string Produce(
            HostModel host,
            string hostNamespace,
            string hostTypeName,
            IReadOnlyCollection<string> servable
            )
        {
            var roots = host.Subjects
                .Where(s => s.IsRoot && servable.Contains(s.MethodSuffix))
                .ToList();

            var builder = new SourceBuilder();

            builder.Line("// <auto-generated/>");
            builder.Line("#pragma warning disable");
            builder.Line("#nullable enable");
            builder.Line();
            builder.Line("namespace " + hostNamespace + ";");
            builder.Line();

            EmitFormatter(builder, host, hostTypeName, roots);
            EmitExtensions(builder);

            return builder.ToString();
        }

        private static void EmitFormatter(
            SourceBuilder builder,
            HostModel host,
            string hostTypeName,
            IReadOnlyList<SubjectModel> roots
            )
        {
            builder.Line("/// <summary>");
            builder.Line("/// Читает тело запроса прямо из трубы, не дожидаясь его целиком.");
            builder.Line("/// </summary>");
            builder.OpenBlock("internal sealed class " + FormatterTypeName + " : " + InputFormatter);

            builder.OpenBlock("internal " + FormatterTypeName + "()");
            builder.Line("SupportedMediaTypes.Add(\"application/json\");");
            builder.Line("SupportedMediaTypes.Add(\"text/json\");");
            builder.Line("SupportedMediaTypes.Add(\"application/*+json\");");
            builder.CloseBlock();
            builder.Line();

            builder.Line("/// <summary>Потолок на недочитанную конструкцию - у эталона такой защиты нет вовсе.</summary>");
            builder.Line(
                "public int MaximumPendingValueLength { get; set; } = "
                + "global::JsonGoddess.Internal.JsonStreamReader<object>.DefaultCap;"
                );
            builder.Line();

            builder.OpenBlock("protected override bool CanReadType(global::System.Type type)");

            var conditions = new List<string>();

            foreach (var root in roots)
            {
                conditions.Add("type == typeof(" + root.FullName + "[])");
                conditions.Add("type == typeof(" + List + "<" + root.FullName + ">)");

                if (TryReaderProducer.ReadsByProperty(root, host.Guards))
                {
                    conditions.Add("type == typeof(" + root.FullName + ")");
                }
            }

            builder.Line("return " + string.Join("\r\n    || ", conditions) + ";");
            builder.CloseBlock();
            builder.Line();

            builder.Line("/// <summary>");
            builder.Line("/// Кодировка проверяется отдельно от типа: читатель работает по UTF-8,");
            builder.Line("/// а эталонный форматтер умеет и другие. Запрос с чужой кодировкой мы не");
            builder.Line("/// заявляем - его дочитает штатный форматтер, стоящий следом.");
            builder.Line("/// </summary>");
            builder.OpenBlock("public override bool CanRead(" + FormatterContext + " context)");
            builder.OpenBlock("if (!base.CanRead(context))");
            builder.Line("return false;");
            builder.CloseBlock();
            builder.Line();
            builder.Line("var contentType = context.HttpContext.Request.ContentType;");
            builder.Line();
            builder.OpenBlock("if (contentType is null)");
            builder.Line("return true;");
            builder.CloseBlock();
            builder.Line();
            builder.Line(
                "var charset = contentType.IndexOf(\"charset=\", "
                + "global::System.StringComparison.OrdinalIgnoreCase);"
                );
            builder.Line();
            builder.OpenBlock("if (charset < 0)");
            builder.Line("return true;");
            builder.CloseBlock();
            builder.Line();
            builder.Line(
                "return contentType.IndexOf(\"utf-8\", charset, "
                + "global::System.StringComparison.OrdinalIgnoreCase) >= 0;"
                );
            builder.CloseBlock();
            builder.Line();

            builder.OpenBlock(
                "public override async " + Task + "<" + FormatterResult + "> ReadRequestBodyAsync("
                + FormatterContext + " context)"
                );

            builder.Line("var pipe = context.HttpContext.Request.BodyReader;");
            builder.Line("var cancellationToken = context.HttpContext.RequestAborted;");
            builder.Line("var cap = MaximumPendingValueLength;");
            builder.Line();

            //Объявленная длина тела - признак «приехало целиком», без которого
            //быстрый путь почти не срабатывает: у мелкого тела первое же
            //обращение к трубе приносит его полностью, но IsCompleted при этом
            //ещё ложно. Нет заголовка (chunked) - нет и признака, и это честно:
            //тогда работает автомат.
            builder.Line("var expectedLength = context.HttpContext.Request.ContentLength ?? -1;");
            builder.Line();
            builder.OpenBlock("try");

            foreach (var root in roots)
            {
                EmitBranch(
                    builder, hostTypeName, root.FullName + "[]",
                    "StreamReadArray_" + root.MethodSuffix
                    );

                EmitBranch(
                    builder, hostTypeName, List + "<" + root.FullName + ">",
                    "StreamReadList_" + root.MethodSuffix
                    );

                if (TryReaderProducer.ReadsByProperty(root, host.Guards))
                {
                    EmitBranch(
                        builder, hostTypeName, root.FullName,
                        "StreamReadOne_" + root.MethodSuffix
                        );
                }
            }

            //CanReadType уже сказал "да" на все типы, которые мы обслуживаем,
            //так что сюда попасть нельзя; молчаливая неудача лучше исключения,
            //которое обвалило бы запрос вместо отступления
            builder.Line("return await " + FormatterResult + ".FailureAsync().ConfigureAwait(false);");

            builder.CloseBlock();
            builder.OpenBlock("catch (" + DocumentException + " failure)");

            //Ключ - путь, ровно как у штатного форматтера, который берёт его из
            //JsonException.Path. Именно ключ клиенты разбирают машинно; текст
            //сообщения у нас свой, и это объявленное расхождение
            builder.Line(
                "context.ModelState.TryAddModelError(failure.Path ?? string.Empty, failure.Message);"
                );
            builder.Line("return " + FormatterResult + ".Failure();");
            builder.CloseBlock();
            builder.OpenBlock("catch (global::System.FormatException failure)");

            //второе семейство отказа: лексема законна, а разобрать её нечем -
            //путь у такого отказа не строился, и ключ остаётся пустым, как и
            //у эталона на не-JSON-ошибке
            builder.Line("context.ModelState.TryAddModelError(string.Empty, failure.Message);");
            builder.Line("return " + FormatterResult + ".Failure();");
            builder.CloseBlock();

            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitBranch(
            SourceBuilder builder,
            string hostTypeName,
            string modelType,
            string method
            )
        {
            builder.OpenBlock("if (context.ModelType == typeof(" + modelType + "))");
            builder.Line(
                "var value = await " + hostTypeName + "." + method + "("
                );
            builder.Indent();
            builder.Line(Injector + ".Instance, pipe, cap, expectedLength, cancellationToken");
            builder.Line(").ConfigureAwait(false);");
            builder.Unindent();
            builder.Line();

            //NoValue, а не Success(null), и это снято пробой: штатный форматтер
            //отвечает так на всякое тело, разобравшееся в null (в том числе на
            //литерал "null"), а MVC уже из этого делает отказ с пустым ключом.
            //Success(null) дал бы 400 с другим набором ключей.
            builder.Line(
                "return value is null ? " + FormatterResult + ".NoValue() : " + FormatterResult + ".Success(value);"
                );

            builder.CloseBlock();
            builder.Line();
        }

        private static void EmitExtensions(SourceBuilder builder)
        {
            builder.Line("/// <summary>");
            builder.Line("/// Включение потокового чтения тела запроса - одна строка в Program.cs:");
            builder.Line("/// <c>builder.Services.AddControllers(o => o.AddJsonGoddess());</c>");
            builder.Line("/// </summary>");
            builder.OpenBlock("internal static class " + ExtensionsTypeName);

            builder.Line("/// <summary>");
            builder.Line("/// Ставится ПЕРВЫМ: форматтеры опрашиваются по порядку, и штатный");
            builder.Line("/// json-форматтер согласится читать всё, до чего мы не дотянулись.");
            builder.Line("/// </summary>");
            builder.OpenBlock("internal static " + MvcOptions + " AddJsonGoddess(this " + MvcOptions + " options)");
            builder.Line("options.InputFormatters.Insert(0, new " + FormatterTypeName + "());");
            builder.Line("return options;");
            builder.CloseBlock();

            builder.CloseBlock();
            builder.Line();
        }
    }
}
